
package com.pkg.hotelbooking;

import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.LinkedList;
import javax.swing.*;

public class HotelbookingUI extends javax.swing.JFrame {

    public HotelbookingUI() {
        initComponents();
        main.getContentPane().setBackground( new java.awt.Color(245, 245,240) );
        main.setUI(null);
        jList1.setBackground(new java.awt.Color(245, 245,240));
    }
    
    private int user_id; //user that just booked a hotel room
    private String manager_hotel = null; //hotel name corresponding to the connected manager
    private boolean ManagerConnected=false; //if manager is connected
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilterMenu = new javax.swing.JPopupMenu();
        Wifi = new javax.swing.JCheckBoxMenuItem();
        Fridge = new javax.swing.JCheckBoxMenuItem();
        View = new javax.swing.JCheckBoxMenuItem();
        BookDialog = new javax.swing.JDialog();
        Submit = new javax.swing.JButton();
        Breakfast = new javax.swing.JCheckBox();
        NameTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        BookSuccess = new javax.swing.JDialog();
        Booked = new javax.swing.JLabel();
        ViewBookings = new javax.swing.JButton();
        Success = new javax.swing.JLabel();
        ViewBookingsDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllBookings = new javax.swing.JTextArea();
        ManagerRegister = new javax.swing.JDialog();
        Username = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ManagerPhone = new javax.swing.JLabel();
        ManagerPhoneTextField = new javax.swing.JTextField();
        ManagerName = new javax.swing.JLabel();
        ManagerNameField = new javax.swing.JTextField();
        ManagerEmail = new javax.swing.JLabel();
        ManagerEmailField = new javax.swing.JTextField();
        HotelName = new javax.swing.JLabel();
        HotelNameField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        ManagerLogin = new javax.swing.JDialog();
        Username1 = new javax.swing.JLabel();
        UsernameTextField1 = new javax.swing.JTextField();
        Password1 = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        ConnectButton = new javax.swing.JButton();
        ViewHotelRoomsDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        RoomsList = new javax.swing.JList<>();
        ViewReservationsDialog = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        ReservationsList = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        main = new javax.swing.JInternalFrame();
        where = new javax.swing.JTextField();
        num_people = new javax.swing.JTextField();
        date_from = new javax.swing.JTextField();
        date_to = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Title = new javax.swing.JLabel();
        uth_logo = new javax.swing.JLabel();
        filterButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        Manager = new javax.swing.JMenu();
        Register = new javax.swing.JMenuItem();
        Login = new javax.swing.JMenuItem();
        ManagerPanel = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        RoomIDTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        CapacityTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PriceTextField = new javax.swing.JTextField();
        hasWifi = new javax.swing.JCheckBox();
        hasFridge = new javax.swing.JCheckBox();
        hasView = new javax.swing.JCheckBox();
        CapacityTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PriceTextField1 = new javax.swing.JTextField();
        hasWifi1 = new javax.swing.JCheckBox();
        hasFridge1 = new javax.swing.JCheckBox();
        hasView1 = new javax.swing.JCheckBox();
        RoomIDTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        RoomCount = new javax.swing.JLabel();
        HotelNameLabel = new javax.swing.JLabel();
        RevenueLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        Wifi.setText("Wifi");
        FilterMenu.add(Wifi);

        Fridge.setText("Fridge");
        FilterMenu.add(Fridge);

        View.setText("View");
        FilterMenu.add(View);

        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });

        Breakfast.setText("Breakfast?");

        NameTextField.setText("Name");

        PhoneTextField.setText("Phone");

        EmailTextField.setText("Email");

        AddressTextField.setText("Address");

        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Name");

        Phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Phone.setText("Phone");

        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email");

        Address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address.setText("Address");

        javax.swing.GroupLayout BookDialogLayout = new javax.swing.GroupLayout(BookDialog.getContentPane());
        BookDialog.getContentPane().setLayout(BookDialogLayout);
        BookDialogLayout.setHorizontalGroup(
            BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Breakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Submit)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BookDialogLayout.setVerticalGroup(
            BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Name)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Phone)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Email)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Address)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Breakfast)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Submit)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Booked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ViewBookings.setText("View all my bookings");
        ViewBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewBookingsMouseClicked(evt);
            }
        });

        Success.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Success.setText("Success!");

        javax.swing.GroupLayout BookSuccessLayout = new javax.swing.GroupLayout(BookSuccess.getContentPane());
        BookSuccess.getContentPane().setLayout(BookSuccessLayout);
        BookSuccessLayout.setHorizontalGroup(
            BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookSuccessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Success, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookSuccessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Booked, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookSuccessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewBookings)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BookSuccessLayout.setVerticalGroup(
            BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookSuccessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Success)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookSuccessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Booked)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(BookSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookSuccessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewBookings)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        AllBookings.setColumns(20);
        AllBookings.setRows(5);
        jScrollPane2.setViewportView(AllBookings);

        javax.swing.GroupLayout ViewBookingsDialogLayout = new javax.swing.GroupLayout(ViewBookingsDialog.getContentPane());
        ViewBookingsDialog.getContentPane().setLayout(ViewBookingsDialogLayout);
        ViewBookingsDialogLayout.setHorizontalGroup(
            ViewBookingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ViewBookingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewBookingsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ViewBookingsDialogLayout.setVerticalGroup(
            ViewBookingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ViewBookingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewBookingsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Username.setText("Username");

        UsernameTextField.setText("username");
        UsernameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameTextFieldMouseClicked(evt);
            }
        });

        Password.setText("Password");

        PasswordField.setText("password");

        ManagerPhone.setText("Phone");

        ManagerPhoneTextField.setText("phone");

        ManagerName.setText("Name");

        ManagerNameField.setText("name");

        ManagerEmail.setText("Email");

        ManagerEmailField.setText("email");

        HotelName.setText("Hotel Name");

        HotelNameField.setText("hotel_name");
        HotelNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelNameFieldMouseClicked(evt);
            }
        });

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerRegisterLayout = new javax.swing.GroupLayout(ManagerRegister.getContentPane());
        ManagerRegister.getContentPane().setLayout(ManagerRegisterLayout);
        ManagerRegisterLayout.setHorizontalGroup(
            ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegisterButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HotelNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ManagerRegisterLayout.setVerticalGroup(
            ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Username)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Password)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerPhone)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerName)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerEmail)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ManagerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegisterButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HotelName)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HotelNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Username1.setText("Username");

        UsernameTextField1.setText("username");

        Password1.setText("Password");

        ConnectButton.setText("Connect");
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerLoginLayout = new javax.swing.GroupLayout(ManagerLogin.getContentPane());
        ManagerLogin.getContentPane().setLayout(ManagerLoginLayout);
        ManagerLoginLayout.setHorizontalGroup(
            ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ConnectButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ManagerLoginLayout.setVerticalGroup(
            ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Username1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Password1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(ManagerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ConnectButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        RoomsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(RoomsList);

        javax.swing.GroupLayout ViewHotelRoomsDialogLayout = new javax.swing.GroupLayout(ViewHotelRoomsDialog.getContentPane());
        ViewHotelRoomsDialog.getContentPane().setLayout(ViewHotelRoomsDialogLayout);
        ViewHotelRoomsDialogLayout.setHorizontalGroup(
            ViewHotelRoomsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ViewHotelRoomsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewHotelRoomsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ViewHotelRoomsDialogLayout.setVerticalGroup(
            ViewHotelRoomsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ViewHotelRoomsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewHotelRoomsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ReservationsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(ReservationsList);

        javax.swing.GroupLayout ViewReservationsDialogLayout = new javax.swing.GroupLayout(ViewReservationsDialog.getContentPane());
        ViewReservationsDialog.getContentPane().setLayout(ViewReservationsDialogLayout);
        ViewReservationsDialogLayout.setHorizontalGroup(
            ViewReservationsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ViewReservationsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewReservationsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ViewReservationsDialogLayout.setVerticalGroup(
            ViewReservationsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ViewReservationsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewReservationsDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(180, 200, 210));
        main.setVisible(true);

        where.setText("Volos");

        num_people.setText("1");

        date_from.setText("13-01-2024");

        date_to.setText("15-01-2024");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Where to?");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("How many?");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("From (dd-MM-yyyy):");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("To (dd-MM-yyyy):");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pkg/hotelbooking/2992771-200.png"))); // NOI18N
        Title.setText("Hotel Booking");

        uth_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pkg/hotelbooking/UTH-logo-english.png"))); // NOI18N

        filterButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        filterButton.setText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        Manager.setText("Manager");

        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        Manager.add(Register);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Manager.add(Login);

        jMenuBar1.add(Manager);

        main.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main.getContentPane());
        main.getContentPane().setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addComponent(uth_logo)
                .addGap(15, 15, 15))
            .addComponent(jSeparator2)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(where, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num_people, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(date_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(date_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(searchButton)
                        .addGap(40, 40, 40))))
            .addComponent(jSeparator1)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(filterButton)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(uth_logo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(where, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_people, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(filterButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Home", main);

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pkg/hotelbooking/2992771-200.png"))); // NOI18N
        Title1.setText("Hotel Booking");

        jButton2.setText("Add room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove room");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Room number:");

        jButton4.setText("Update room");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setText("Capacity:");

        jLabel7.setText("Price:");

        hasWifi.setText("Wifi");

        hasFridge.setText("Fridge");

        hasView.setText("View");

        jLabel8.setText("Capacity:");

        jLabel9.setText("Price:");

        hasWifi1.setText("Wifi");

        hasFridge1.setText("Fridge");

        hasView1.setText("View");

        jLabel10.setText("Room number:");

        RoomCount.setText("No. of Rooms: ");

        HotelNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        HotelNameLabel.setText("Hotel");

        RevenueLabel.setText("Total Revenue");

        jButton5.setText("View Rooms");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("View Reservations");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerPanelLayout = new javax.swing.GroupLayout(ManagerPanel);
        ManagerPanel.setLayout(ManagerPanelLayout);
        ManagerPanelLayout.setHorizontalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RoomIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(47, 47, 47))
            .addComponent(jSeparator5)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomCount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addComponent(HotelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RevenueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CapacityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hasWifi1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasView1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasFridge1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButton4)
                .addGap(50, 50, 50))
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(CapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hasView, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)))
                .addComponent(jButton2)
                .addGap(67, 67, 67))
        );
        ManagerPanelLayout.setVerticalGroup(
            ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerPanelLayout.createSequentialGroup()
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Title1)
                            .addComponent(HotelNameLabel))
                        .addGap(8, 8, 8)
                        .addComponent(RoomCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RevenueLabel))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasWifi)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasFridge)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(hasView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RoomIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(PriceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapacityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addComponent(hasWifi1)
                        .addGap(14, 14, 14)
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasFridge1)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(hasView1))
                    .addGroup(ManagerPanelLayout.createSequentialGroup()
                        .addGroup(ManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(RoomIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        if(ManagerConnected){

            jTabbedPane1.addTab("Manager", ManagerPanel);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static class MultiLineCellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                      boolean isSelected, boolean cellHasFocus) {
            Component renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (renderer instanceof JLabel) {
                JLabel label = (JLabel) renderer;
                label.setText("<html>" + stylizeText(value.toString()) + "</html>");
            }
            if (isSelected) {
                renderer.setBackground(new java.awt.Color(245, 245,240));
                renderer.setForeground(Color.BLACK);
            }
            return renderer;
        }

        private String stylizeText(String text) {
            String[] words = text.split("\\u2605", 2);
            if (words.length > 1) {
                String firstWord = words[0];
                String restOfString = words[1];
                char c = '\u2605';
                return "<span style='font-size:130%'>" + firstWord +"</span>"+c+ restOfString.replace("\n", "<br>");
            }
            words = text.split("\\s", 2);
            if(words.length>1){
                if(words[0].equalsIgnoreCase("No"))
                    return text;
                if(words[0].equalsIgnoreCase("room")){
                    String[] temp=words[1].split("\\s",2);
                    return "<span style='font-size:130%'>" + words[0]+" "+temp[0] + "<br></span>" + temp[1].replace("\n", "<br>");
                }
            }
            return text;
        }
    }
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        Queries Q = new Queries();
        
        LinkedList list = Q.search(where.getText(), Integer.parseInt(num_people.getText()), date_from.getText(),
                date_to.getText(),View.isSelected(),Fridge.isSelected(),Wifi.isSelected());
        
        DefaultListModel demoList = new DefaultListModel();
        for(int i=0;i<list.size();i++){
            demoList.addElement(list.get(i));
        }
        jList1 = new JList(demoList);
        jList1.setCellRenderer(new MultiLineCellRenderer());
        jScrollPane1.setViewportView(jList1);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        ManagerLogin.setLayout(new GridLayout(3,2));
        
        ManagerLogin.add(Username1);
        ManagerLogin.add(UsernameTextField1);
        ManagerLogin.add(Password1);
        ManagerLogin.add(PasswordField1);
        ManagerLogin.add(ConnectButton);
        ManagerLogin.pack();
        
        ManagerLogin.setSize(200, 150);
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - ManagerLogin.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - ManagerLogin.getHeight()) / 2;
        
        ManagerLogin.setLocation(x, y);
        ManagerLogin.setVisible(!ManagerLogin.isVisible());
    }//GEN-LAST:event_LoginActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        FilterMenu.setLocation(filterButton.getLocation().x , filterButton.getLocation().y+135);
        FilterMenu.setVisible(!FilterMenu.isVisible());
    }//GEN-LAST:event_filterButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BookDialog.setLayout(new GridLayout(5,2));
        
        BookDialog.add(Email);
        BookDialog.add(EmailTextField);
        BookDialog.add(Name);
        BookDialog.add(NameTextField);
        BookDialog.add(Address);
        BookDialog.add(AddressTextField);
        BookDialog.add(Phone);
        BookDialog.add(PhoneTextField);
        BookDialog.add(Breakfast);
        BookDialog.add(Submit);
        
        Point parentLocation = this.getLocationOnScreen();

        int x = parentLocation.x + (this.getWidth() - BookDialog.getWidth()) / 2;

        int y = parentLocation.y + (this.getHeight() - BookDialog.getHeight()) / 2;
        
        BookDialog.pack();
        //BookDialog.setPreferredSize(new Dimension(200,200));
        BookDialog.setSize(350, 250);
        BookDialog.setLocation(x, y);
        BookDialog.setVisible(!BookDialog.isVisible());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        
        if(jList1.getSelectedValue()==null)
            return;
        
        String[] info = jList1.getSelectedValue().split("\\u2605");
        
        String hotel_name = info[0].substring(0, info[0].length()-2);
        
        info = jList1.getSelectedValue().split("\n");
        String[] tmp = info[2].split(" ");
        
        int room_number = Integer.parseInt(tmp[1]);
        Userbook user = new Userbook(PhoneTextField.getText(),AddressTextField.getText(),NameTextField.getText(), EmailTextField.getText());
        Hotel hotel = new Hotel(hotel_name);
        user_id=user.getId();
        
        LocalDate startDate = LocalDate.parse(date_from.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        LocalDate endDate = LocalDate.parse(date_to.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        int num_nights = Math.toIntExact(ChronoUnit.DAYS.between(startDate, endDate)); // Calculate the number of nights between the two dates
        
        Reservation NewReservation = new Reservation(user.getId(),room_number,hotel.getId(),date_from.getText(),num_nights,Breakfast.isSelected());
        if(!user.find(PhoneTextField.getText()))
            user.insert(user);
        NewReservation.insert(NewReservation);
        
        user.closeConnection();
        hotel.closeConnection();
        NewReservation.closeConnection();
        
        BookSuccess.setLayout(new GridLayout(3,1));
        Success.setPreferredSize(new Dimension(200,50));
        BookSuccess.add(Success);
        Booked.setText("Booked "+hotel_name+" room "+room_number);
        Booked.setPreferredSize(new Dimension(200,50));
        BookSuccess.add(Booked);
        BookSuccess.add(ViewBookings);
        BookSuccess.pack();
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - BookDialog.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - BookDialog.getHeight()) / 2;
        
        BookSuccess.setLocation(x, y);
        BookSuccess.setVisible(!BookSuccess.isVisible());
        BookDialog.setVisible(false);
    }//GEN-LAST:event_SubmitMouseClicked

    private void ViewBookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBookingsMouseClicked
        ViewBookingsDialog.setLayout(new BorderLayout());
        AllBookings.setText(Queries.UserReservations(user_id));
        
        ViewBookingsDialog.add(AllBookings);
        ViewBookingsDialog.setSize(250, 250);
        ViewBookingsDialog.pack();
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - BookDialog.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - BookDialog.getHeight()) / 2;
        
        ViewBookingsDialog.setLocation(x, y);
        ViewBookingsDialog.setVisible(!ViewBookingsDialog.isVisible());
        BookSuccess.setVisible(false);
    }//GEN-LAST:event_ViewBookingsMouseClicked

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        ManagerRegister.setLayout(new GridLayout(7,2));
        ManagerRegister.add(ManagerName);
        ManagerRegister.add(ManagerNameField);
        
        ManagerRegister.add(ManagerPhone);
        ManagerRegister.add(ManagerPhoneTextField);
        
        ManagerRegister.add(ManagerEmail);
        ManagerRegister.add(ManagerEmailField);
        ManagerRegister.add(Username);
        ManagerRegister.add(UsernameTextField);
        ManagerRegister.add(Password);
        ManagerRegister.add(PasswordField);
        ManagerRegister.add(HotelName);
        ManagerRegister.add(HotelNameField);
        
        ManagerRegister.add(RegisterButton);
        ManagerRegister.pack();
        
        ManagerRegister.setSize(300, 250);
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - ManagerRegister.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - ManagerRegister.getHeight()) / 2;
        
        ManagerRegister.setLocation(x, y);
        ManagerRegister.setVisible(!ManagerRegister.isVisible());
    }//GEN-LAST:event_RegisterActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        
        Hotel hotel=new Hotel(HotelNameField.getText());
        
        if(!hotel.find(HotelNameField.getText())){
            HotelNameField.setBackground(Color.red);
            return;
        }
        Manager manager = new Manager(hotel.getId(),UsernameTextField.getText(),String.valueOf(PasswordField.getPassword()),ManagerPhoneTextField.getText(),
                                        ManagerNameField.getText(),ManagerEmailField.getText());
        if(manager.find(UsernameTextField.getText())){
            UsernameTextField.setBackground(Color.red);
            return;
        }
        manager.insert(manager);
        hotel.closeConnection();
        manager.closeConnection();
        ManagerRegister.setVisible(false);
        
        //open login
        ManagerLogin.setLayout(new GridLayout(3,2));
        UsernameTextField1.setText(UsernameTextField.getText());
        ManagerLogin.add(Username1);
        ManagerLogin.add(UsernameTextField1);
        ManagerLogin.add(Password1);
        ManagerLogin.add(PasswordField1);
        ManagerLogin.add(ConnectButton);
        ManagerLogin.pack();
        
        ManagerLogin.setSize(200, 150);
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - ManagerLogin.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - ManagerLogin.getHeight()) / 2;
        
        ManagerLogin.setLocation(x, y);
        ManagerLogin.setVisible(true);
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void UsernameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameTextFieldMouseClicked
        UsernameTextField.setBackground(RegisterButton.getBackground());
    }//GEN-LAST:event_UsernameTextFieldMouseClicked

    private void HotelNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotelNameFieldMouseClicked
        HotelNameField.setBackground(RegisterButton.getBackground());
    }//GEN-LAST:event_HotelNameFieldMouseClicked

    private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtonActionPerformed
        boolean correct=Queries.ManagerCheckCredentials(UsernameTextField1.getText(),String.valueOf(PasswordField1.getPassword()));
        
        if(!correct)
            return;
        ManagerConnected = true;
        manager_hotel = Queries.getHotelName(UsernameTextField1.getText());
        
        RoomCount.setText("No. of Rooms: " + Queries.getNumOfRooms(manager_hotel));
        RevenueLabel.setText("Total Revenue: " + Queries.getTotalRevenue(manager_hotel)+"€");
        HotelNameLabel.setText(manager_hotel);
        ManagerLogin.setVisible(false);
        ManagerPanel.setBackground( new java.awt.Color(245, 245,240) );
        jTabbedPane1.addTab("Manager", ManagerPanel);
        jTabbedPane1.setSelectedComponent(ManagerPanel);
    }//GEN-LAST:event_ConnectButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Hotel h = new Hotel(manager_hotel);
        HotelRoom r = new HotelRoom(Integer.parseInt(RoomIDTextField.getText()), manager_hotel);
        
        r.delete(r.getId(), h.getId());
        RoomCount.setText("No. of Rooms: " + Queries.getNumOfRooms(manager_hotel));
        
        r.closeConnection();
        h.closeConnection();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Hotel h = new Hotel(manager_hotel);
        
        HotelRoom NewRoom = new HotelRoom(h, Integer.parseInt(PriceTextField.getText()),
                Integer.parseInt(CapacityTextField.getText()),
        hasView.isSelected(), hasFridge.isSelected(), hasWifi.isSelected());
        
        NewRoom.insert(NewRoom);
        RoomCount.setText("No. of Rooms: " + Queries.getNumOfRooms(manager_hotel));
        
        NewRoom.closeConnection();
        h.closeConnection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Hotel h = new Hotel(manager_hotel);
        
        HotelRoom r = new HotelRoom(Integer.parseInt(RoomIDTextField1.getText()), h.getName());
        
        r.update(r.getId(), h.getId(), Integer.parseInt(PriceTextField1.getText()),
                Integer.parseInt(CapacityTextField1.getText()),
                hasView1.isSelected(), hasFridge1.isSelected(), hasWifi1.isSelected());
        
        r.closeConnection();
        h.closeConnection();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        LinkedList<String> list=Queries.ViewRooms(manager_hotel);
        
        DefaultListModel demoList = new DefaultListModel();
        for(int i=0;i<list.size();i++){
            demoList.addElement(list.get(i));
        }
        RoomsList = new JList(demoList);
        RoomsList.setCellRenderer(new MultiLineCellRenderer());
        jScrollPane3.setViewportView(RoomsList);
        ViewHotelRoomsDialog.add(jScrollPane3);
        ViewHotelRoomsDialog.pack();
        
        ViewHotelRoomsDialog.setSize(300, 250);
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - ViewHotelRoomsDialog.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - ViewHotelRoomsDialog.getHeight()) / 2;
        
        ViewHotelRoomsDialog.setLocation(x, y);
        
        ViewHotelRoomsDialog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        LinkedList<String> list=Queries.ViewReservations(manager_hotel);
        
        DefaultListModel demoList = new DefaultListModel();
        for(int i=0;i<list.size();i++){
            demoList.addElement(list.get(i));
        }
        ReservationsList = new JList(demoList);
        ReservationsList.setCellRenderer(new MultiLineCellRenderer());
        jScrollPane4.setViewportView(ReservationsList);
        ViewReservationsDialog.add(jScrollPane4);
        ViewReservationsDialog.pack();
        
        ViewReservationsDialog.setSize(300, 250);
        Point parentLocation = this.getLocationOnScreen();
        int x = parentLocation.x + (this.getWidth() - ViewReservationsDialog.getWidth()) / 2;
        int y = parentLocation.y + (this.getHeight() - ViewReservationsDialog.getHeight()) / 2;
        
        ViewReservationsDialog.setLocation(x, y);
        
        ViewReservationsDialog.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelbookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelbookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelbookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelbookingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /******************
                 * Remove the comment from the below line in order to setup the database.
                 * ONLY CALL THE SETUP FUNCTION ONCE!
                 * Add the comment after the database is filled.
                 */
                //DBManager.setup();
                /**********************/
                
                new HotelbookingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextArea AllBookings;
    private javax.swing.JDialog BookDialog;
    private javax.swing.JDialog BookSuccess;
    private javax.swing.JLabel Booked;
    private javax.swing.JCheckBox Breakfast;
    private javax.swing.JTextField CapacityTextField;
    private javax.swing.JTextField CapacityTextField1;
    private javax.swing.JButton ConnectButton;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPopupMenu FilterMenu;
    private javax.swing.JCheckBoxMenuItem Fridge;
    private javax.swing.JLabel HotelName;
    private javax.swing.JTextField HotelNameField;
    private javax.swing.JLabel HotelNameLabel;
    private javax.swing.JMenuItem Login;
    private javax.swing.JMenu Manager;
    private javax.swing.JLabel ManagerEmail;
    private javax.swing.JTextField ManagerEmailField;
    private javax.swing.JDialog ManagerLogin;
    private javax.swing.JLabel ManagerName;
    private javax.swing.JTextField ManagerNameField;
    private javax.swing.JPanel ManagerPanel;
    private javax.swing.JLabel ManagerPhone;
    private javax.swing.JTextField ManagerPhoneTextField;
    private javax.swing.JDialog ManagerRegister;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JTextField PriceTextField1;
    private javax.swing.JMenuItem Register;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JList<String> ReservationsList;
    private javax.swing.JLabel RevenueLabel;
    private javax.swing.JLabel RoomCount;
    private javax.swing.JTextField RoomIDTextField;
    private javax.swing.JTextField RoomIDTextField1;
    private javax.swing.JList<String> RoomsList;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Success;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JTextField UsernameTextField1;
    private javax.swing.JCheckBoxMenuItem View;
    private javax.swing.JButton ViewBookings;
    private javax.swing.JDialog ViewBookingsDialog;
    private javax.swing.JDialog ViewHotelRoomsDialog;
    private javax.swing.JDialog ViewReservationsDialog;
    private javax.swing.JCheckBoxMenuItem Wifi;
    private javax.swing.JTextField date_from;
    private javax.swing.JTextField date_to;
    private javax.swing.JButton filterButton;
    private javax.swing.JCheckBox hasFridge;
    private javax.swing.JCheckBox hasFridge1;
    private javax.swing.JCheckBox hasView;
    private javax.swing.JCheckBox hasView1;
    private javax.swing.JCheckBox hasWifi;
    private javax.swing.JCheckBox hasWifi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JInternalFrame main;
    private javax.swing.JTextField num_people;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel uth_logo;
    private javax.swing.JTextField where;
    // End of variables declaration//GEN-END:variables
}
